CREATE DATABASE IMDB_PROJECT;
USE IMDB_PROJECT;
CREATE TABLE IMDB(
    POSTER_LINK VARCHAR(500),
    SERIES_TITLE VARCHAR(250),
    RELEASED_YEAR INT,
    CERTIFICATE VARCHAR(15),
    RUN_TIME VARCHAR(15),
    GENRE VARCHAR(225),
    IMDB_RATING DECIMAL(3,1),
    OVERVIEW TEXT,
    META_SCORE INT,
    DIRECTOR VARCHAR(100),
    STAR1 VARCHAR(100),


-- BUSSINESS PROBLEM AND SOLUTIONS
USE IMDB_PROJECT;
-- 1.COUNT BY MOVIES BY CERTIFICATES (U,UA,A,ETC.)
SELECT CERTIFICATE,COUNT(*) AS MOVIE_COUNT
FROM imdb_dataset
WHERE Certificate IS NOT NULL
group by CERTIFICATE
ORDER BY MOVIE_COUNT DESC;

-- 2 MOST COMMON GENRE IN TOP 100 GROSSING MOVIES
SELECT genre,count(*) as count
from (
select genre 
from imdb_dataset 
where gross is not null
order by gross DESC
LIMIT 100
) AS TOP_MOVIE
GROUP BY GENRE
ORDER BY COUNT DESC;

-- 3 LIST ALL MOVIES RELEASED IN 2010
SELECT SERIES_TITLE ,IMDB_RATING,GENRE 
FROM imdb_dataset
WHERE RELEASED_YEAR=2010;

-- 4 TOP 5 DIRECTORS BY AVERAGE IMDB RATING
SELECT DIRECTOR , ROUND(AVG(IMDB_RATING),2) AS AVG_RATING,COUNT(*) AS MOVIE_COUNT
FROM imdb_dataset
WHERE IMDB_RATING IS NOT NULL
GROUP BY DIRECTOR
HAVING COUNT(*)>=3
ORDER BY AVG_RATING DESC
LIMIT 5;
-- 5 MOVIES WITH THE LOGEST RUN TIME
SELECT SERIES_TITLE ,RUNTIME
FROM IMDB_DATASET
WHERE RUNTIME IS NOT NULL
ORDER BY CAST(SUBSTRING_INDEX(RUNTIME,' ',1) AS UNSIGNED) DESC
LIMIT 1;

-- 6 COUNT OF  MOVIES RELEASED EACH YEAR
SELECT RELEASED_YEAR,COUNT(*) AS TOTAL_MOVIES
FROM imdb_dataset
GROUP BY RELEASED_YEAR
ORDER BY RELEASED_YEAR;

-- 7 ALL MOVIES BY DIRECTOR "CHRISTOPHER NOLAN"
SELECT SERIES_TITLE,RELEASED_YEAR,IMDB_RATING
FROM IMDB_DATASET
WHERE DIRECTOR ="CHRISTOPHER NOLAN";

-- 8 TOP 5 ACTORS WHO APPEAR MOST OFTEN
SELECT STAR,COUNT(*) AS APPEARANCES
FROM (
SELECT STAR1 AS STAR FROM IMDB_DATASET
UNION ALL
SELECT STAR2 AS STAR FROM IMDB_DATASET
UNION ALL
SELECT STAR3 AS STAR FROM IMDB_DATASET
UNION ALL 
SELECT STAR4 AS STAR FROM IMDB_DATASET
) AS ALL_STARS
GROUP BY star
ORDER BY APPEARANCES DESC 
LIMIT 5;

-- 9 NO OF MOVIES PER GENRE
SELECT GENRE ,COUNT(*) AS MOVIE_COUNT
FROM imdb_dataset
GROUP BY GENRE 
ORDER BY MOVIE_COUNT DESC;

-- 10 LIST ALL MOVIES WHOSE OVERVIEW CONTAINS "REVENGE" OR "MURDER"
SELECT SERIES_TITLE,IMDB_RATING,OVERVIEW
FROM imdb_dataset
WHERE Overview LIKE "%REVENGE%" OR OVERVIEW LIKE "%MURDER%";

    STAR2 VARCHAR(100),
    STAR3 VARCHAR(100),
    STAR4 VARCHAR(100),
    NO_OF_VOTES INT,
    GROSS BIGINT
    );
