CREATE DATABASE IMDB_PROJECT;
USE IMDB_PROJECT;
CREATE TABLE IMDB(
    POSTER_LINK VARCHAR(500),
    SERIES_TITLE VARCHAR(250),
    RELEASED_YEAR INT,
    CERTIFICATE VARCHAR(15),
    RUN_TIME VARCHAR(15),
    GENRE VARCHAR(225),
    IMDB_RATING DECIMAL(3,1),
    OVERVIEW TEXT,
    META_SCORE INT,
    DIRECTOR VARCHAR(100),
    STAR1 VARCHAR(100),
    STAR2 VARCHAR(100),
    STAR3 VARCHAR(100),
    STAR4 VARCHAR(100),
    NO_OF_VOTES INT,
    GROSS BIGINT
    );
